add contributing to PyMC
data-umbrella/data-umbrella-website pull request #122
Opened 2023-03-19 14:22 UTC by SangamSwadiK

## Description: What does this implement/fix? Explain your changes.
 
Adds contributing to PyMC

## Reference: Issue or Pull Request (PR)
- [x] Towards #87 

## Reminders

- [x] Did you review the [CONTRIBUTING GUIDE](https://github.com/data-umbrella/data-umbrella-website/blob/main/CONTRIBUTING.md)?
- [x] Did you reference an issue or another pull request?

#### Any other comments?
None

2023-03-19 14:48 UTC, reshamas commented
@SangamSwadiK Thanks for this PR.
a) I think for filters, we should use:
- contributing (~~video~~)
- using-pymc (~~pymc-resource~~)

b) For ArviZ thumbnail, we can use this one as a start (may need resizing):
https://www.canva.com/design/DAFTXBr6mxg/9QnMuzbCHObGl049DcdJpg/edit?utm_content=DAFTXBr6mxg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

c) For "Contributing to PyMC Documentation", let's start with this thumbnail:
https://www.canva.com/design/DAE6rZJAdA0/GB-izEd0N7fTbbCWZ6gIrA/edit?utm_content=DAE6rZJAdA0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

c) In the navigation bar, I would move "Contributing to PyMC" above the "core python" one.

d) Can we update this title to "PyMC" and not "PyMC3" (remove ref to version 3):
Intuitive Bayesian modeling with PyMC3 

e) The current links in the 3rd row point to the YouTube video.  I think we can point them to:
- Intuitive Bayesian Modeling with PyMC: https://pymc-data-umbrella.xyz/en/latest/about/intuitive_modeling/index.html
- etc.

2023-03-19 14:48 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +    - title: "Intuitive Bayesian modeling with PyMC3"
```suggestion
    - title: "Intuitive Bayesian Modeling with PyMC"
```

2023-03-19 14:48 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +    - title: "An example Pull Request(PR) to PyMC"
```suggestion
    - title: "An Example Pull Request (PR) to PyMC"
```

2023-03-19 14:49 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +    - title: "Contributing to PyMC documentation"
```suggestion
    - title: "Contributing to PyMC Documentation"
```

2023-03-19 14:49 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +    - title: "Intro to Numpy array operations"
```suggestion
    - title: "Intro to Numpy Array Operations"
```

2023-03-19 14:50 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource_url: ""
```suggestion
      resource_url: "https://pymc-data-umbrella.xyz/en/latest/about/probabilistic_programming_with_pymc/index.html"
```

2023-03-19 14:50 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource_url: "https://youtu.be/6dc7JgR8eI0"
```suggestion
      resource_url: "https://pymc-data-umbrella.xyz/en/latest/about/intuitive_modeling/index.html"
```

2023-03-19 14:51 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource_url: "https://youtu.be/Iq0dY5hU4D4"
```suggestion
      resource_url: "https://pymc-data-umbrella.xyz/en/latest/about/contributing_to_pymc/index.html"
```

2023-03-19 14:52 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource_url: "https://youtu.be/oud3Jd1FJ7c"
```suggestion
      resource_url: "https://pymc-data-umbrella.xyz/en/latest/about/intro_to_array_operations/index.html"
```

2023-03-20 11:07 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +        - using-pymc
```suggestion
        - contributing
        - using-pymc
```

2023-03-20 11:07 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource: "contributing "
```suggestion
      resource: "contributing"
```

2023-03-20 11:07 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      sub_title: "contributing "
```suggestion
      sub_title: "contributing"
```

2023-03-20 11:07 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource: "contributing "
```suggestion
      resource: "contributing"
```

2023-03-20 11:13 UTC, reshamas requested changes

2023-03-20 11:13 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      sub_title: "contributing "
```suggestion
      sub_title: "contributing"
```

2023-03-20 11:13 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      sub_title: "contributing "
```suggestion
      sub_title: "contributing"
```

2023-03-20 11:13 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource: "using-pymc"
```suggestion
      resource: "Outline and resources"
```

2023-03-20 11:13 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource: "using-pymc"
```suggestion
      resource: "Outline and resources"
```

2023-03-20 11:13 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource: "contributing "
```suggestion
      resource: "Outline and resources"
```

2023-03-23 11:56 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource: "using-pymc"
```suggestion
      resource: "Outline and resources"
```

2023-03-23 11:57 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource_url: "https://youtu.be/457ZTes4xOI"
```suggestion
      resource_url: "https://youtu.be/457ZTes4xOI"
```

2023-03-23 12:06 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +</h4>
```suggestion
  We have extensive resources on <a href="https://pymc-data-umbrella.xyz/en/latest/2023-03_sprint/index.html">Contributing to PyMC</a>.  
</h4>
```

2023-03-23 12:39 UTC, OriolAbril commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource_url: "https://youtu.be/457ZTes4xOI"
I did not but could do it if you prefer linking there than linking to the video directly

2023-03-23 12:42 UTC, reshamas commented on snowlake-v1.2/open-source/contributing-to-pymc.html
> +      resource: "using-pymc"
```suggestion
      resource: "video"
```

2023-03-23 12:43 UTC, reshamas commented
Thank you @SangamSwadiK.
Nice to have the PyMC resources on one page! I think people will find it useful.

2023-03-23 12:43 UTC, merged