Add about team
data-umbrella/data-umbrella-website pull request #26
Opened 2022-12-17 05:44 UTC by SangamSwadiK

## PR Overview

#### Type of contribution
- [x] Code
- [ ] Documentation

#### Reference: Issue or Pull Request (PR)
- [x] Towards #15  
- [ ] Fixes #xxx. See also #xxx   [this will close the referenced issue or PR]
- [ ] Resolves #xxx, #xxx [for multiple issues, this will close them]

## Description: What does this implement/fix? Explain your changes.
- Updates the Team Info using (https://www.dataumbrella.org/about/team)
- Added profile images in  `/assets/images/team`

#### Reminders

- [x] Did you review the [CONTRIBUTING GUIDE](https://github.com/data-umbrella/data-umbrella-website/blob/main/CONTRIBUTING.md)?
- [x] Did you reference an issue or another pull request?

#### Any other comments?
The Description and designation are marked as TBD(to be done) as I could not find them at
https://www.dataumbrella.org/about/team

Please let me know in case of changes.
Will fix them.

Thanks.

2022-12-19 13:58 UTC, symeneses requested changes
Thanks @SangamSwadiK, this was fast! 
It's needed to add a submenu under about us with the page `team_members` located in `snowlake-v1.2/_includes/team_members.html`. The menu is configured in `snowlake-v1.2/_data/navigation.yml`.  As it is now,  it is not visible.

@reshamas should we keep the field description? AFAIK, we don't have one.

2022-12-19 18:04 UTC, reshamas commented
@symeneses 
We can remove it. You mean this "Save your time and money
by choosing our professional team."

2022-12-19 18:55 UTC, symeneses commented
No, the description for every member of the team.

2022-12-20 14:54 UTC, symeneses commented on snowlake-v1.2/_data/navigation.yml
> +        url: "/team_members"
The page is not in the template folder, we will have to copy from the folder `_includes`.

2022-12-20 17:00 UTC, symeneses commented on snowlake-v1.2/_data/navigation.yml
> +        url: "/team_members"
Not move it, but copy the file. Afterwards, we can clean the repo a bit so that we keep the template apart from the actual pages we are using.

2022-12-20 17:10 UTC, reshamas commented on snowlake-v1.2/_data/team_carousel.yml
> +    designation: "Executive Director"
```suggestion
    designation: "Director"
```

2022-12-20 17:11 UTC, reshamas commented on snowlake-v1.2/_data/team_carousel.yml
> +    designation: "TBD"
```suggestion
    designation: "Data Science Community Manager"
```

2023-01-06 17:18 UTC, symeneses commented on snowlake-v1.2/_data/navigation.yml
> +        url: "/team_members"
Hi @SangamSwadiK,
Sorry for my late reply, got busy the last days of the year.
I was checking and we have to leave the files in `_include` and the new .html file created it should be like this:

```html
---
layout: page
title: "Meet the team"
header_image: "/assets/images/art/bg9.jpg"
header_style: "one"

teams_carousel:
  enable: true
  type: blob

---
<!-- Team Wrapper -->
{% if page.teams_carousel.enable%}
  {% include team_members.html %}
{% endif %}
  <!-- /.Team Wrapper -->
```

The new file is needed as the template has the carousel inside a about.html, so we need to create a new one and then include (add files in the _include folder) the pages from the template. Let me know if this is clear.

2023-02-07 14:46 UTC, merged